<?php

App::uses('AppModel', 'Model');

class Country extends AppModel
{

    public $useTable = 'countries';
    public $validate = [
        'name' => [
            'rule'    => 'isUnique',
            'message' => 'country_name_duplicate'
        ]
    ];

    public function getCountryCodeByCountryId($id)
    {
        $country = $this->find('first', ['conditions' => ['_id' => $id]]);

        return isset($country['Country']['code']) ? $country['Country']['code'] : NULL;
    }

    /**
     * get list country name + country code which have status equal two
     * @return array
     */
    public function getListCountryCode()
    {
        $conditions = [
            'status' => 2
        ];
        if (isset($_GET['lang_code']) && $_GET['lang_code']) {
            $conditions['lang_code'] = $_GET['lang_code'];
        }
        return $country = $this->find('list', ['conditions' => $conditions, 'fields' => ['code', 'name']]);
    }

    public function getCountryIdByCountryCode($code)
    {
        $country = $this->find('first', ['conditions' => ['code' => $code]]);

        return isset($country['Country']['id']) ? $country['Country']['id'] : null;
    }

    public function afterFind($results, $primary = false)
    {
        return parent::afterFind($results, $primary); // TODO: Change the autogenerated stub
    }


    public $customSchema = array(
        'id'          => '',
        'ref_id'          => '',
        'name'        => '',
        'code'        => '',
        'loc'         => array(
            'type'        => '',
            'coordinates' => '',
        ),
        'latitude'    => '',
        'longitude'   => '',
        'dial_code'   => '',
        'description' => '',
        'order'       => '',
        'status'      => '',
        'lang_code'   => '',
        'user'        => '',
        'created'     => '',
        'modified'    => '',
    );

}
