<?php

class CouponBehavior extends ModelBehavior
{
    public function afterSave(Model $model, $created, $options = array())
    {
        parent::afterSave($model, $created, $options); // TODO: Change the autogenerated stub

        if (!$created) {
            if (isset($model->data[$model->alias]['coupon']) && $model->data[$model->alias]['coupon']) {
                App::uses('Coupon', 'Model');
                $Coupon = new Coupon();
                $coupon = $Coupon->find('first', [
                    'conditions' => $model->data[$model->alias]['coupon']
                ]);
                $coupon['Coupon']['object_name'] = $model->data[$model->alias]['name'];
                $coupon['Coupon']['object_file_uris']['logo'] = $model->data[$model->alias]['file_uris']['logo'];
            }
        }
    }

}