<?php

App::uses('AppController', 'Controller');

class CountriesController extends AppController
{

    public $uses = array('Country');

    public function beforeFilter()
    {
        parent::beforeFilter(); // TODO: Change the autogenerated stub
        // nếu không có quyền truy cập, thì buộc user phải đăng xuất
        if (!$this->isAllow()) {

            return $this->redirect($this->Auth->loginRedirect);
        }
        $this->setInit();
    }

    public function index()
    {
        $options = [
            'order' => array('modified' => 'DESC')
        ];

        $this->setSearchConds($options);
        $this->Paginator->settings = $options;
        $list_data = $this->Paginator->paginate($this->modelClass);

        $this->set([
            'breadcrumb' => [
                array(
                    'url'   => Router::url(array('action' => 'index')),
                    'label' => __('country_title'),
                )
            ],
            'page_title' => __('country_title'),
            'list_data'  => $list_data
        ]);
    }

    public function add()
    {
        $this->saveRequestData();

        $this->set([
            'breadcrumb' => [
                array(
                    'url'   => Router::url(array('action' => 'index')),
                    'label' => __('country_title'),
                ),
                array(
                    'url'   => Router::url(array('action' => __FUNCTION__)),
                    'label' => __('add_action_title'),
                )
            ],
            'page_title' => __('country_title')
        ]);
    }

    public function edit($id = null)
    {
        if (!$this->{$this->modelClass}->exists($id)) {
            throw new NotFoundException(__('invalid_data'));
        }

        $this->saveRequestData();

        $this->setRequestData($id);

        $this->set([
            'breadcrumb' => [
                array(
                    'url'   => Router::url(array('action' => 'index')),
                    'label' => __('country_title'),
                ),
                array(
                    'url'   => Router::url(array('action' => __FUNCTION__, $id)),
                    'label' => __('edit_action_title'),
                )
            ],
            'page_title' => __('country_title')
        ]);

        $this->render('add');
    }

    public function cloneRecord($id = null)
    {
        if (!$this->{$this->modelClass}->exists($id)) {
            throw new NotFoundException(__('invalid_data'));
        }

        $this->saveRequestData();

        $this->setRequestData($id, true);

        $this->set([
            'breadcrumb' => [
                array(
                    'url'   => Router::url(array('action' => 'index')),
                    'label' => __('country_title'),
                ),
                array(
                    'url'   => Router::url(array('action' => __FUNCTION__, $id)),
                    'label' => __('clone_action_title'),
                )
            ],
            'page_title' => __('country_title')
        ]);

        $this->render('add');
    }

    protected function setSearchConds(&$options)
    {

        if (isset($this->request->query['name']) && strlen(trim($this->request->query['name'])) > 0) {

            $name = trim($this->request->query['name']);
            $this->request->query['name'] = $name;
            $options['conditions']['name']['$regex'] = new MongoRegex("/" . mb_strtolower($name) . "/i");
        }

        if (isset($this->request->query['code']) && strlen(trim($this->request->query['code'])) > 0) {

            $code = trim($this->request->query['code']);
            $this->request->query['code'] = $code;
            $options['conditions']['code']['$regex'] = new MongoRegex("/" . mb_strtolower($code) . "/i");
        }

        if (isset($this->request->query['dial_code']) && strlen(trim($this->request->query['dial_code'])) > 0) {

            $dial_code = trim($this->request->query['dial_code']);
            $this->request->query['dial_code'] = $dial_code;
            $options['conditions']['dial_code']['$regex'] = new MongoRegex("/" . mb_strtolower($dial_code) . "/i");
        }

        if (isset($this->request->query['order']) && strlen($this->request->query['order']) > 0) {
            $order = (int)$this->request->query['order'];
            $this->request->query['order'] = $order;
            $options['conditions']['order']['$eq'] = $order;
        }

        if (isset($this->request->query['status']) && strlen($this->request->query['status']) > 0) {

            $status = (int)$this->request->query['status'];
            $options['conditions']['status']['$eq'] = $status;
        }
    }

    protected function setInit()
    {
        $this->set('model_name', $this->modelClass);
        $this->set('status', Configure::read('sysconfig.App.status'));
    }

    private function saveRequestData()
    {
        if ($this->request->is('post') || $this->request->is('put')) {

            if ($this->{$this->modelClass}->save($this->request->data[$this->modelClass])) {

                $this->Session->setFlash(__('save_successful_message'), 'default', array(), 'good');
                $this->redirect(array('action' => 'index'));
            } else {

                $this->Session->setFlash(__('save_error_message'), 'default', array(), 'bad');
            }
        }
    }

    /**
     * @param $id
     * @param bool $clone
     */
    private function setRequestData($id, $clone = false)
    {
        $this->request->data = $this->{$this->modelClass}->find('first', array(
            'conditions' => array(
                'id' => new MongoId($id),
            ),
        ));

        if ($clone && isset($this->request->data[$this->modelClass]['id'])) {
            $this->request->data[$this->modelClass]['ref_id'] = $this->request->data[$this->modelClass]['id'];
            unset($this->request->data[$this->modelClass]['id']);
        }
    }
}
